import React from 'react';
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from '@react-pdf/renderer';

// Register fonts
Font.register({
  family: 'Inter',
  src: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiA.woff2',
});

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    padding: 30,
    fontFamily: 'Inter',
  },
  header: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#1f2937',
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#374151',
  },
  text: {
    fontSize: 12,
    lineHeight: 1.5,
    color: '#6b7280',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 10,
    color: '#9ca3af',
  },
});

interface ProposalTemplateProps {
  title: string;
  clientName: string;
  description: string;
  price: number;
  currency: string;
  validUntil: string;
}

export const ProposalTemplate: React.FC<ProposalTemplateProps> = ({
  title,
  clientName,
  description,
  price,
  currency,
  validUntil,
}) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text>Proposal: {title}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Client</Text>
        <Text style={styles.text}>{clientName}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Description</Text>
        <Text style={styles.text}>{description}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Price</Text>
        <Text style={styles.text}>
          {price} {currency}
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Valid Until</Text>
        <Text style={styles.text}>{validUntil}</Text>
      </View>

      <View style={styles.footer}>
        <Text>Generated by Jamb Platform</Text>
      </View>
    </Page>
  </Document>
);
